#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pylama
Version  : 7.4.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/43/8d/8c8b58b54bb94013db1710e047195b706d93c383f8afa0a343cdaf81969f/pylama-7.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/43/8d/8c8b58b54bb94013db1710e047195b706d93c383f8afa0a343cdaf81969f/pylama-7.4.3.tar.gz
Summary  : pylama -- Code audit tool for python
Group    : Development/Tools
License  : LGPL-3.0
Requires: pylama-bin = %{version}-%{release}
Requires: pylama-license = %{version}-%{release}
Requires: pylama-python = %{version}-%{release}
Requires: pylama-python3 = %{version}-%{release}
Requires: mccabe
Requires: pycodestyle
Requires: pydocstyle
Requires: pyflakes
BuildRequires : buildreq-distutils3

%description
#############

%package bin
Summary: bin components for the pylama package.
Group: Binaries
Requires: pylama-license = %{version}-%{release}

%description bin
bin components for the pylama package.


%package license
Summary: license components for the pylama package.
Group: Default

%description license
license components for the pylama package.


%package python
Summary: python components for the pylama package.
Group: Default
Requires: pylama-python3 = %{version}-%{release}

%description python
python components for the pylama package.


%package python3
Summary: python3 components for the pylama package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pylama package.


%prep
%setup -q -n pylama-7.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538081979
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pylama
cp LICENSE %{buildroot}/usr/share/package-licenses/pylama/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pylama

%files license
%defattr(-,root,root,-)
/usr/share/package-licenses/pylama/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
